production: &default
  schedule_dispatch:
    class: ScheduleDispatchJob
    queue: default
    schedule: every minute
  data_builder_cleanup:
    class: DataBuilder::CleanupJob
    queue: default
    schedule: every day at 3am
  disk_usage:
    class: DiskUsageJob
    queue: default
    schedule: every hour

development: *default
