#!/usr/bin/env ruby
# coding: utf-8

# A special case converter for Cooperar

require 'se_open_data/setup'
require 'se_open_data/csv/schema/types'
require 'se_open_data/lookup'
#require 'normalize_country'



# A class which defines callback methods #on_header, #on_row, and #on_end, 
# that are called during the conversion process.
class Observer < SeOpenData::CSV::Schema::Observer
  Types = SeOpenData::CSV::Schema::Types

  # Set up anything persistent you need here  
  def initialize(setup:)
    super()

    # Create a geocoder
    @geocoder = setup.geocoder
  end

  def url(text)
    return if text == '' || text == nil
    Types.normalise_url(text, throw: true)
  end

  # Called with an array of header fields, and a field_map, which
  # is an array of integers denoting the schema index for each header
  def on_header(header:, field_map:)
    @ix = 0
  end
  
  def on_row(
        # These parameters match source schema field ids
        id:,
        name:,
        descr:,
        country_id:,
        addr:,
        cwca:,
        cwcbmc:,
        ncui_cat:
      )

    @ix += 1

    # protect against empty names 
    raise "Empty name at row #{@ix}" unless name.to_s != "" 
    
    warn "row #{@ix} #{name}; #{addr}"
    # country_id = NormalizeCountry(country)
    geocoded = @geocoder.call(addr)

    cc = geocoded&.original&.data&.dig("properties", "country_code")&.upcase
    if cc != "IN"
      warn "geocoding is not in India, ignoring. #{[id, name, cc, addr]}"
      geocoded = nil
    end

    # Replace these with the actual values to write.
    # You may yield zero or many times if desired, and the equivalent number
    # of rows will be emitted.
    yield id: id,
          name: name,
          description: descr,
          organisational_structure: nil,
          primary_activity: nil,
          activities: nil,
          street_address: nil,
          locality: nil,
          region: nil,
          postcode: nil,
          country_id: "IN",
          territory_id: nil,
          homepage: nil,
          phone: nil,
          email: nil,
          twitter: nil,
          facebook: nil,
          companies_house_number: nil,
          qualifiers: nil,
          base_membership_type: nil,
          latitude: nil,
          longitude: nil,
          geocontainer: geocoded&.osm_uri,
          geocontainer_lat: geocoded&.lat,
          geocontainer_lon: geocoded&.lng,
          geocontainer_confidence: geocoded&.confidence,
          geocoded_addr: addr
  end
  
  # Called after all the rows have been processed
  def on_end
  end

end

SeOpenData::Setup
  .new
  .convert_with(observer: Observer)
