---
id: :mersey_green
name: Mersey Green
version: 20200620
primary_key:
- :id
comment: 
fields:
- id: :id
  header: id
  desc: A unique identifier for this initiative
  comment: ''
- id: :submitdate
  header: submitdate
  desc: ''
  comment: ''
- id: :lastpage
  header: lastpage
  desc: ''
  comment: ''
- id: :startlanguage
  header: startlanguage
  desc: ''
  comment: ''
- id: :seed
  header: seed
  desc: ''
  comment: ''
- id: :startdate
  header: startdate
  desc: ''
  comment: ''
- id: :datestamp
  header: datestamp
  desc: ''
  comment: ''
- id: :ipaddr
  header: ipaddr
  desc: ''
  comment: ''
- id: :refurl
  header: refurl
  desc: ''
  comment: ''
- id: :name
  header: name
  desc: ''
  comment: ''
- id: :address_a
  header: address[a]
  desc: ''
  comment: ''
- id: :address_b
  header: address[b]
  desc: ''
  comment: ''
- id: :address_c
  header: address[c]
  desc: ''
  comment: ''
- id: :locality
  header: address[d]
  desc: ''
  comment: ''
- id: :postcode
  header: address[e]
  desc: ''
  comment: ''
- id: :address_a1
  header: address[a1]
  desc: ''
  comment: ''
- id: :location
  header: location
  desc: ''
  comment: ''
- id: :email
  header: contactEmail
  desc: ''
  comment: ''
- id: :phone
  header: contactPhone
  desc: ''
  comment: ''
- id: :website
  header: website
  desc: ''
  comment: ''
- id: :facebook
  header: facebook
  desc: ''
  comment: ''
- id: :twitter
  header: twitter
  desc: ''
  comment: ''
- id: :description
  header: description
  desc: ''
  comment: ''
- id: :activity
  header: activity
  desc: ''
  comment: ''
- id: :network
  header: network
  desc: ''
  comment: ''
- id: :websiteConsent
  header: websiteConsent
  desc: ''
  comment: ''
- id: :contactName
  header: contactName
  desc: ''
  comment: ''
- id: :contactConsent_SQ001
  header: contactConsent[SQ001]
  desc: ''
  comment: ''
- id: :contactConsent_SQ002
  header: contactConsent[SQ002]
  desc: ''
  comment: ''
- id: :suggestedInitiatives
  header: suggestedInitiatives
  desc: ''
  comment: ''
- id: :approved
  header: approved
  desc: Will be "Yes" if this initiative has been validated and approved by an admin
  comment: Initiatives should only be imported if they are approved.
- id: :community_group
  header: structure[SQ001]
  desc: ''
  comment: ''
- id: :non_profit
  header: structure[SQ002]
  desc: ''
  comment: ''
- id: :social_enterprise
  header: structure[SQ003]
  desc: ''
  comment: ''
- id: :charity
  header: structure[SQ004]
  desc: ''
  comment: ''
- id: :company
  header: structure[SQ005]
  desc: ''
  comment: ''
- id: :workers_coop
  header: structure[SQ006]
  desc: ''
  comment: ''
- id: :housing_coop
  header: structure[SQ007]
  desc: ''
  comment: ''
- id: :consumer_coop
  header: structure[SQ008]
  desc: ''
  comment: ''
- id: :producer_coop
  header: structure[SQ009]
  desc: ''
  comment: ''
- id: :stakeholder_coop
  header: structure[SQ010]
  desc: ''
  comment: ''
- id: :community_interest_company
  header: structure[SQ011]
  desc: ''
  comment: ''
- id: :community_benefit_society
  header: structure[SQ012]
  desc: ''
  comment: ''
- id: :values_SQ001
  header: values[SQ001]
  desc: ''
  comment: ''
- id: :values_SQ002
  header: values[SQ002]
  desc: ''
  comment: ''
- id: :values_SQ003
  header: values[SQ003]
  desc: ''
  comment: ''
- id: :values_SQ004
  header: values[SQ004]
  desc: ''
  comment: ''
- id: :values_SQ005
  header: values[SQ005]
  desc: ''
  comment: ''
- id: :arts
  header: secondaryActivities[SQ002]
  desc: ''
  comment: ''
- id: :campaigning
  header: secondaryActivities[SQ003]
  desc: ''
  comment: ''
- id: :community
  header: secondaryActivities[SQ004]
  desc: ''
  comment: ''
- id: :education
  header: secondaryActivities[SQ005]
  desc: ''
  comment: ''
- id: :energy
  header: secondaryActivities[SQ006]
  desc: ''
  comment: ''
- id: :food
  header: secondaryActivities[SQ007]
  desc: ''
  comment: ''
- id: :goods_services
  header: secondaryActivities[SQ008]
  desc: ''
  comment: ''
- id: :health
  header: secondaryActivities[SQ009]
  desc: ''
  comment: ''
- id: :housing
  header: secondaryActivities[SQ010]
  desc: ''
  comment: ''
- id: :money
  header: secondaryActivities[SQ011]
  desc: ''
  comment: ''
- id: :nature
  header: secondaryActivities[SQ012]
  desc: ''
  comment: ''
- id: :reuse
  header: secondaryActivities[SQ013]
  desc: ''
  comment: ''
- id: :agriculture
  header: secondaryActivities[SQ014]
  desc: ''
  comment: ''
- id: :industry
  header: secondaryActivities[SQ015]
  desc: ''
  comment: ''
- id: :utilities
  header: secondaryActivities[SQ016]
  desc: ''
  comment: ''
- id: :transport
  header: secondaryActivities[SQ017]
  desc: ''
  comment: ''
- id: :attendWorkshop
  header: attendWorkshop
  desc: ''
  comment: ''
