#!/usr/bin/env ruby
# coding: utf-8
#
# This script controls a pipeline of processes that convert the original
# CSV data into the se_open_data standard, one step at a time.
#
# We aim to put only logic specific to this project in this file, and
# keep it brief and clear. Shared logic should go into the {SeOpenData}
# library.
#
# This script can be invoked directly, or as part of the {SeOpenData}
# library's command-line API {SeOpenData::Cli}. For example, this
# just runs the conversion step (or specifically: a script in the
# current directory called `converter`):
#
#     seod convert 
#
# And this runs the complete chain of commands generating and
# deploying the linked data for this project, as configured by
# `settings/config.txt`:
#
#     seod run-all
#
# See the documentation on [`seod`]({SeOpenData::Cli}) for more
# information.

require 'se_open_data/setup'
require 'se_open_data/csv/schema/types'
require 'se_open_data/lookup'
#require 'normalize_country'



# A class which defines callback methods #on_header, #on_row, and #on_end, 
# that are called during the conversion process.
class Observer < SeOpenData::CSV::Schema::Observer
  Types = SeOpenData::CSV::Schema::Types

  # Set up anything persistent you need here  
  def initialize(setup:)
    super()

    # Create a geocoder
    @geocoder = setup.geocoder
    # Center coordinates for the Philippines
    @center_lat = 12.8797
    @center_lon = 121.7740
  end

  def url(text)
    return if text == '' || text == nil
    Types.normalise_url(text, throw: true)
  end

  # This was generated using Duck.ai
  #
  # A radius calculated to include all of the Philippine archipelago is 1800km
  def km_from_philippines(latitude, longitude)
    
    # Haversine formula to calculate distance
    dlat = (latitude - @center_lat) * Math::PI / 180
    dlon = (longitude - @center_lon) * Math::PI / 180

    a = Math.sin(dlat / 2) ** 2 +
        Math.cos(@center_lat * Math::PI / 180) * Math.cos(latitude * Math::PI / 180) * Math.sin(dlon / 2) ** 2
    c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a))

    # Distance in kilometers
    distance = 6371 * c

    return distance
  end

  # Called with an array of header fields, and a field_map, which
  # is an array of integers denoting the schema index for each header
  def on_header(header:, field_map:)
    @ix = 0
  end
  
  def on_row(
        # These parameters match source schema field ids
        id:,
        name:,
        city:,
        region:,
        address:
      )

    # Examples of common preliminary steps:
    addr = Types.normalise_addr(address,city,region,'Republic of the Philippines')
    @ix += 1
    return unless name.to_s != "" # protect against empty names (they exist!)
    
    warn "row #{@ix} #{name}; #{addr}"
    # country_id = NormalizeCountry(country)
    geocoded = @geocoder.call(addr)

    # Try to reverse-geocode the location we get, and check if it's in the Phillipines.
    # If not, discard this location
    if geocoded && geocoded&.lat && geocoded&.lng
#      result = @geocoder.call([geocoded.lat, geocoded.lng])
      cc = geocoded.original&.data.dig("properties", "country_code")
      if cc != "ph"
        warn "Geocoder returned Non-Phillipino location, "
        +" ignoring. #{[cc, @ix, name]}"
        geocoded = nil
      end
      # range = km_from_philippines(geocoded.lat, geocoded.lng)
      # if range > 1800
      #   warn "Geocoder returned Phillipino location outide geographic bounds circle,"
      #   +" ignoring. #{[range, @ix, name]}"
      #   geocoded = nil
      # end
    end
    
    # Replace these with the actual values to write.
    # You may yield zero or many times if desired, and the equivalent number
    # of rows will be emitted.
    yield id: @ix,
          name: name,
          description: nil,
          organisational_structure: nil,
          primary_activity: nil,
          activities: nil,
          street_address: address,
          locality: city,
          region: region,
          postcode: nil,
          country_id: 'PH',
          territory_id: nil,
          homepage: nil,
          phone: nil,
          email: nil,
          twitter: nil,
          facebook: nil,
          companies_house_number: nil,
          qualifiers: nil,
          base_membership_type: nil,
          latitude: nil,
          longitude: nil,
          geocontainer: geocoded&.osm_uri,
          geocontainer_lat: geocoded&.lat,
          geocontainer_lon: geocoded&.lng,
          geocontainer_confidence: geocoded&.confidence,
          geocoded_addr: addr
  end
  
  # Called after all the rows have been processed
  def on_end
  end

end

SeOpenData::Setup
  .new
  .convert_with(observer: Observer)
