---
id: :ownedByOxford
name: Owned by Oxford
version: 20210928
primary_key:
- :id
comment: 
fields:
- id: :id
  header: id
  desc: A unique identifier for the organisation
  comment: ''
- id: :name
  header: Organisation Name
  desc: The name of the organisation
  comment: ''
- id: :website
  header: Website
  desc: "The organisation's website"
  comment: ''
- id: :street
  header: Street Address
  desc: "The organisation's main street address"
  comment: ''
- id: :postcode
  header: Post Code
  desc: "The organisation's main address' post code"
  comment: ''
- id: :latitude
  header: Latitude
  desc: "The organisation's main address' latitude"
  comment: ''
- id: :longitude
  header: Longitude
  desc: "The organisation's main address' longitude"
  comment: ''
- id: :description
  header: Description
  desc: "A description of the organisation"
  comment: ''
- id: :type_of_relationship
  header: Type of Relationship
  desc: An optional label defining the organisation's relationship to Owned by Oxford
  comment: Should be a list of English language identifier phrases
- id: :primary_activity
  header: Primary Activity
  desc: "Indicates the organisation's primary activity"
  comment: 'Should be an English activities-modified record ID'
- id: :primary_activity_id
  header: Primary Activity ID
  desc: "Indicates the organisation's primary activity"
  comment: 'Should be an activities-modified vocab ID'
- id: :primary_activity_label
  header: Primary Activity Label
  desc: "Indicates the organisation's primary activity"
  comment: 'Should be an activities-modified vocab label'
- id: :secondary_activities
  header: Activities
  desc: "Indicates the organisation's secondary activities, if any"
  comment: 'Should be zero or more English activities-modified vocab labels, delimited with semi-colons'
- id: :secondary_activity_ids
  header: Activity IDs
  desc: "Indicates the organisation's secondary activities, if any"
  comment: 'Should be zero or more activities-modified vocab IDs, delimited with semi-colons'
- id: :secondary_activity_labels
  header: Activity Labels
  desc: "Indicates the organisation's secondary activities, if any"
  comment: 'Should be zero or more activities-modified record IDs, delimited with semi-colons'
- id: :organisational_structures
  header: Organisational Structure
  desc: "Indicates the organisation's structure(s)"
  comment: 'Should be multiple English organisational-structure vocab labels'
- id: :organisational_structure_ids
  header: Organisational Structure ID
  desc: "Indicates the organisation's structure(s)"
  comment: 'Should be multiple organisational-structure vocab IDs'
- id: :organisational_structure_labels
  header: Organisational Structure Label
  desc: "Indicates the organisation's structure(s)"
  comment: 'Should be multiple organisational-structure record labels'
- id: :ext_uri
  header: "URI (from External Initiative)"
  desc: "The identifying URI field from any linked external initiative row"
  comment: 'Optional. This field, if not empty, indicates there is a linked row'
- id: :ext_name
  header: "Name (from External Initiative)"
  desc: "The Name field from any linked external initiative row"
  comment: 'Optional'
- id: :ext_description
  header: "Description (from External Initiative)"
  desc: "The Description field from any linked external initiative row"
  comment: 'Optional. Free text.'
- id: :ext_street_address
  header: "Street Address (from External Initiative)"
  desc: "The Street Address field from any linked external initiative row"
  comment: 'Optional. Free text, but should be geolocatable.'
- id: :ext_postcode
  header: "Postcode (from External Initiative)"
  desc: "The Postcode field from any linked external initiative row"
  comment: 'Optional. Should be a valid postcode'
- id: :ext_website
  header: "Website (from External Initiative)"
  desc: "The Website URI from any linked external initiative row"
  comment: 'Optional. Should be a valid URL.'
- id: :ext_primary_activity
  header: "Primary Activity (from External Initiative)"
  desc: "The Primary Activity label from any linked external initiative row"
  comment: 'Optional. Note this is expected to be a single English language label, not an ID or URI'
- id: :ext_primary_activity_id
  header: "Primary Activity ID (from External Initiative)"
  desc: "The Primary Activity ID from any linked external initiative row"
  comment: 'Optional. Note this is expected to be an ID, but not a full URI'  
- id: :ext_secondary_activities
  header: " Activities (from External Initiative)"
  desc: "The Activities label from any linked external initiative row"
  comment: 'Optional. Note this is expected to be multiple English language labels delimited by commas, not IDs or URIs'
- id: :ext_secondary_activity_ids
  header: "Activity IDs (from External Initiative)"
  desc: "The Activity IDs from any linked external initiative row"
  comment: 'Optional. Note this is expected to be an ID, but not a full URI'
- id: :ext_organisational_structures
  header: "Organisational Structure (from External Initiative)"
  desc: "The Organisational Structure labels from any linked external initiative row"
  comment: 'Optional. Note this is expected to be a multiple English language labels delimited by commas, not IDs or URIs'
- id: :ext_organisational_structure_ids
  header: "Organisational Structure ID (from External Initiative)"
  desc: "The Organisational Structure IDs from any linked external initiative row"
  comment: 'Optional. Note this is expected to be IDs delimited by commas, but not full URIs'
- id: :ext_latitude
  header: "Latitude (from External Initiative)"
  desc: "The Latitude field from any linked external initiative row"
  comment: 'Optional. Should be a real number in the valid range'
- id: :ext_longitude
  header: "Longitude (from External Initiative)"
  desc: "The Longitude field from any linked external initiative row"
  comment: 'Optional. Should be a real number in the valid range'
- id: :approved
  header: Ready for Map
  desc: "`true` if this data is validated, anything else if it should be ignored"
  comment: ''
