require "set"

# Regular expressions shared by the MykoMap dataset format, ported from
# mykomap-monolith libs/common/src/rxdefs.ts.
module Mykomap
  module Rx
    # URL-safe base64 (RFC4648 sect 5) - used for dataset IDs
    DATASET_ID = /\A[A-Za-z0-9_-]+\z/

    # An XML NCName (no colons), approximated per Regex Cookbook 8.4
    NCNAME_SRC = "[_\\p{Ll}\\p{Lu}\\p{Lt}\\p{Lo}\\p{Nl}][_.\\p{L}\\p{M}\\p{Nd}\\p{Nl}-]*".freeze
    NCNAME = /\A#{NCNAME_SRC}\z/
    # A QName: two NCNames joined by a colon (the colon is required)
    QNAME = /\A#{NCNAME_SRC}:#{NCNAME_SRC}\z/
    # An abbreviated URI: an NCName followed by a colon
    ABBREV_URI = /\A#{NCNAME_SRC}:\z/

    # A prefix URI: http(s) scheme, domain, path, optional trailing #
    DOMAIN_LABEL_SRC = "[A-Za-z](?:[A-Za-z0-9-]*[A-Za-z0-9])?".freeze
    PCT_ENC_SRC = "%[0-9A-Fa-f]{2}".freeze
    PATH_CHAR_SRC = "[A-Za-z0-9._~!$&'()*+,;=:@-]".freeze
    PATH_SEGMENT_SRC = "(?:#{PCT_ENC_SRC}|#{PATH_CHAR_SRC})+".freeze
    PREFIX_URI = %r{\Ahttps?://#{DOMAIN_LABEL_SRC}(?:[.]#{DOMAIN_LABEL_SRC})*(?:/#{PATH_SEGMENT_SRC})*/?#?\z}

    # Item id-or-index path segment; an index is "@<digits>"
    DATASET_ITEM_IX = /\A@\d+\z/
    DATASET_ITEM_ID_OR_IX = /\A#{PATH_SEGMENT_SRC}\z/

    # Vocab term IDs generated by the builder
    TERM_ID = /\A[A-Za-z_][A-Za-z0-9._-]*\z/

    # Admin identifiers (dataset/template/project names)
    ADMIN_ID = /\A[A-Za-z0-9][A-Za-z0-9_-]{0,63}\z/

    # ISO 639-1 set-1 language codes (from libs/common/src/iso639-1.ts)
    ISO639_1_CODES = %w[
      aa ab ae af ak am an ar as av ay az ba be bg bi bm bn bo br bs ca ce ch
      co cr cs cu cv cy da de dv dz ee el en eo es et eu fa ff fi fj fo fr fy
      ga gd gl gn gu gv ha he hi ho hr ht hu hy hz ia id ie ig ii ik io is it
      iu ja jv ka kg ki kj kk kl km kn ko kr ks ku kv kw ky la lb lg li ln lo
      lt lu lv mg mh mi mk ml mn mr ms mt my na nb nd ne ng nl nn no nr nv ny
      oc oj om or os pa pi pl ps pt qu rm rn ro ru rw sa sc sd se sg si sk sl
      sm sn so sq sr ss st su sv sw ta te tg th ti tk tl tn to tr ts tt tw ty
      ug uk ur uz ve vi vo wa wo xh yi yo za zh zu
    ].to_set.freeze
  end
end
