#!/usr/bin/env ruby
# coding: utf-8
#
# This script controls a pipeline of processes that convert the original
# CSV data into the se_open_data standard, one step at a time.
#
# We aim to put only logic specific to this project in this file, and
# keep it brief and clear. Shared logic should go into the {SeOpenData}
# library.
#
# This script can be invoked directly, or as part of the {SeOpenData}
# library's command-line API {SeOpenData::Cli}. For example, this
# just runs the conversion step (or specifically: a script in the
# current directory called `converter`):
#
#     seod convert 
#
# And this runs the complete chain of commands generating and
# deploying the linked data for this project, as configured by
# `settings/config.txt`:
#
#     seod run-all
#
# See the documentation on [`seod`]({SeOpenData::Cli}) for more
# information.

require 'se_open_data/setup'
require 'se_open_data/csv/schema/types'
require 'se_open_data/lookup'
#require 'normalize_country'



# A class which defines callback methods #on_header, #on_row, and #on_end, 
# that are called during the conversion process.
class Observer < SeOpenData::CSV::Schema::Observer
  Types = SeOpenData::CSV::Schema::Types

  # Set up anything persistent you need here  
  def initialize(setup:)
    super()

    # Create a geocoder
    @geocoder = setup.geocoder
    vocabs_file = "vocabs.json"

    # Define the field mappings
    @food_system_category = SeOpenData::Lookup.new
                              .key {|k| k.downcase }
                              # SUBID is the raw identifier, use that as ID is inferred
                              .load_csv('food-system-category.csv', from: 'SUBID', to: 'fsc-short')
    @food_system_subcategory = SeOpenData::Lookup.new
                                 .key {|k| k.downcase }
                                 # ditto
                                 .load_csv('food-system-category.csv', from: 'SUBID', to: 'fsc')
    @locality = SeOpenData::Lookup.new
                  .key {|k| k.downcase }
                  .load_csv('locality.csv', from: 'ID', to: 'loc')
    
  end

  def to_url(text)
    return if text == '' || text == nil
    Types.normalise_url(text.strip, throw: true)
  end

  def to_email(text)
    return if text == '' || text == nil
    Types.normalise_email(text.strip, throw: true)
  end

  def strip(text)
    return if text == '' || text == nil
    return text.strip
  end    

  # Get the first top-level food system category uris
  def primary_food_system_category_id(text)
    # Careful! the input data can have spaces in them.
    val = Types.multivalue_split(text).first.to_s.strip # get the first item, if any
    return @food_system_category[val] # map it
  end

  # Get all the uris, including the implicit top-level 
  def food_system_category_ids(text)
    # Careful! the input data can have spaces in them.
    vals = Types.multivalue_split(text.gsub(' ', ''))
    toplevel_ids = vals.map { |it| @food_system_category[it] }
    other_ids = vals.map { |it| @food_system_subcategory[it] }
    
    return Types.multivalue_join(toplevel_ids.concat(other_ids).uniq)
  end
  
  def locality_id(text)
    return if text == '' || text == nil
    @locality[text]
  end
  
  # Called with an array of header fields, and a field_map, which
  # is an array of integers denoting the schema index for each header
  def on_header(header:, field_map:)
    @ix = 0
  end
  
  def on_row(
        # These parameters match source schema field ids
        id:,
        title_en:,
        title_cy:,
        locality:,
        locality_id:,
        food_system_category_names:,
        food_system_categories:,
        food_system_subcategory_names:,
        food_system_subcategories:,
        popup_text_en:,
        popup_text_cy:,
        address:,
        postcode:,
        contact_name:,
        email:,
        phone:,
        homepage:,
        on_lx:,
        notes:,
        update_contact:
      )
    @ix += 1
    
    # Normalise the ID and skip rows with an empty id
    id = id.to_s.strip
    return if id == "" 

    # Normalise the address
    addr = if address.to_s.strip == ''
             nil
           else
             Types.normalise_addr(address, postcode, "GB")
           end

    warn "row #{@ix}: #{id}, #{addr}"
    # country_id = NormalizeCountry(country)
    geocoded = @geocoder.call(addr) if addr != nil

    # Replace these with the actual values to write.
    # You may yield zero or many times if desired, and the equivalent number
    # of rows will be emitted.
    yield id: id,
          name: strip(title_en),
          description: strip(popup_text_en),
          organisational_structure: nil,
          primary_activity: nil,
          activities: nil,
          street_address: strip(address),
          locality: strip(locality),
          region: nil,
          postcode: strip(postcode),
          country_id: 'GB',
          territory_id: nil,
          homepage: to_url(homepage),
          phone: strip(phone),
          email: to_email(email),
          twitter: nil,
          facebook: nil,
          companies_house_number: nil,
          qualifiers: nil,
          base_membership_type: nil,
          latitude: nil,
          longitude: nil,
          geocontainer: geocoded&.osm_uri,
          geocontainer_lat: geocoded&.lat,
          geocontainer_lon: geocoded&.lng,
          geocontainer_confidence: geocoded&.confidence,
          geocoded_addr: addr,
          name_cy: strip(title_cy),
          description_cy: strip(popup_text_cy),
          primary_food_system_category_id: primary_food_system_category_id(food_system_subcategories),
          food_system_category_ids: food_system_category_ids(food_system_subcategories),
          locality_id: locality_id(locality_id)

  end
  
  # Called after all the rows have been processed
  def on_end
  end

end

SeOpenData::Setup
#  .new(input_file_opts: 'r:windows-1252:utf-8') # read Windows-1252 into UTF-8
  .new
  .convert_with(observer: Observer)
