#!/usr/bin/env ruby
# coding: utf-8
#
# This script controls a pipeline of processes that convert the original
# CSV data into the se_open_data standard, one step at a time.
#
# We aim to put only logic specific to this project in this file, and
# keep it brief and clear. Shared logic should go into the {SeOpenData}
# library.
#
# This script can be invoked directly, or as part of the {SeOpenData}
# library's command-line API {SeOpenData::Cli}. For example, this
# just runs the conversion step (or specifically: a script in the
# current directory called `converter`):
#
#     seod convert 
#
# And this runs the complete chain of commands generating and
# deploying the linked data for this project, as configured by
# `settings/config.txt`:
#
#     seod run-all
#
# See the documentation on [`seod`]({SeOpenData::Cli}) for more
# information.

require 'se_open_data/setup'
require 'se_open_data/csv/schema/types'
require 'se_open_data/lookup'
require 'normalize_country'



# A class which defines callback methods #on_header, #on_row, and #on_end, 
# that are called during the conversion process.
class Observer < SeOpenData::CSV::Schema::Observer
  # Local alias for a long-named symbol
  Types = SeOpenData::CSV::Schema::Types
  
  def to_url(text)
    return if text == '' || text == nil
    Types.normalise_url(text, throw: true)
  end
  
  def initialize(setup:)
    super()

    # Create a geocoder
    @geocoder = setup.geocoder
  end

  # Called with an array of header fields, and a field_map, which
  # is an array of integers denoting the schema index for each header
  def on_header(header:, field_map:)
    @ix = 0
  end

  def on_row(
        # Thesexo parameters match source schema field ids
        id: ,
        name: ,
        website: ,
        latitude: ,
        longitude: ,
        address: ,
        postcode: ,
        city: ,
        state_region: ,
        country_id: ,
        org_structure: ,
        membership_type: ,
        activities_ica: ,
        description: 
      )
    
    country = NormalizeCountry(country_id)
    addr = Types.normalise_addr(address, city, state_region, country, postcode)
    # warn "row #{@ix} #{addr}"
    geocoded = @geocoder.call(addr)
    @ix += 1
    
    yield id: id,
          name: name,
          description: description,
          organisational_structure: org_structure,
          primary_activity: activities_ica,
          activities: nil,
          street_address: address,
          locality: city,
          region: state_region,
          postcode: postcode,
          country_id: country_id,
          territory_id: nil,
          homepage: to_url(website),
          phone: nil,
          email: nil,
          twitter: nil,
          facebook: nil,
          companies_house_number: nil,
          qualifiers: nil,
          base_membership_type: membership_type,
          latitude: latitude,
          longitude: longitude,
          geocontainer: geocoded&.osm_uri,
          geocontainer_lat: geocoded&.lat,
          geocontainer_lon: geocoded&.lng,
          geocontainer_confidence: geocoded&.confidence,
          geocoded_addr: addr
  end
   
  # Called after all the rows have been processed
  def on_end
  end

end


SeOpenData::Setup
  .new(input_file_opts: 'r:windows-1252:utf-8') # read Windows-1252 into UTF-8
  .convert_with(observer: Observer)
