---
id: :newbridge
name: Solidarity NE
version: 20200620
primary_key:
- :id
comment: 
fields:
- id: :id
  header: id
  desc: A unique identifier for this initiative
  comment: ''
- id: :submitdate
  header: submitdate
  desc: ''
  comment: ''
- id: :lastpage
  header: lastpage
  desc: ''
  comment: ''
- id: :startlanguage
  header: startlanguage
  desc: ''
  comment: ''
- id: :seed
  header: seed
  desc: ''
  comment: ''
- id: :startdate
  header: startdate
  desc: ''
  comment: ''
- id: :datestamp
  header: datestamp
  desc: ''
  comment: ''
- id: :ipaddr
  header: ipaddr
  desc: ''
  comment: ''
- id: :refurl
  header: refurl
  desc: ''
  comment: ''
- id: :name
  header: name
  desc: ''
  comment: ''
- id: :address_a
  header: address[a]
  desc: ''
  comment: ''
- id: :address_b
  header: address[b]
  desc: ''
  comment: ''
- id: :address_c
  header: address[c]
  desc: ''
  comment: ''
- id: :address_d
  header: address[d]
  desc: ''
  comment: ''
- id: :address_e
  header: address[e]
  desc: ''
  comment: ''
- id: :address_a1
  header: address[a1]
  desc: ''
  comment: ''
- id: :location
  header: location
  desc: ''
  comment: ''
- id: :email
  header: contactEmail
  desc: ''
  comment: ''
- id: :phone
  header: contactPhone
  desc: ''
  comment: ''
- id: :website
  header: website
  desc: ''
  comment: ''
- id: :facebook
  header: facebook
  desc: ''
  comment: ''
- id: :twitter
  header: twitter
  desc: ''
  comment: ''
- id: :description
  header: description
  desc: ''
  comment: ''
- id: :activity
  header: activity
  desc: ''
  comment: ''
- id: :network
  header: network
  desc: ''
  comment: ''
- id: :websiteConsent
  header: websiteConsent
  desc: ''
  comment: ''
- id: :contactName
  header: contactName
  desc: ''
  comment: ''
- id: :contactConsent_SQ001
  header: contactConsent[SQ001]
  desc: ''
  comment: ''
- id: :contactConsent_SQ002
  header: contactConsent[SQ002]
  desc: ''
  comment: ''
- id: :suggestedInitiatives
  header: suggestedInitiatives
  desc: ''
  comment: ''
- id: :approved
  header: approved
  desc: Will be "Yes" if this initiative has been validated and approved by an admin
  comment: Initiatives should only be imported if they are approved.
- id: :structure_SQ001
  header: structure[SQ001]
  desc: ''
  comment: ''
- id: :structure_SQ002
  header: structure[SQ002]
  desc: ''
  comment: ''
- id: :structure_SQ003
  header: structure[SQ003]
  desc: ''
  comment: ''
- id: :structure_SQ004
  header: structure[SQ004]
  desc: ''
  comment: ''
- id: :structure_SQ005
  header: structure[SQ005]
  desc: ''
  comment: ''
- id: :structure_SQ006
  header: structure[SQ006]
  desc: ''
  comment: ''
- id: :structure_SQ007
  header: structure[SQ007]
  desc: ''
  comment: ''
- id: :structure_SQ008
  header: structure[SQ008]
  desc: ''
  comment: ''
- id: :structure_SQ009
  header: structure[SQ009]
  desc: ''
  comment: ''
- id: :structure_SQ010
  header: structure[SQ010]
  desc: ''
  comment: ''
- id: :structure_SQ011
  header: structure[SQ011]
  desc: ''
  comment: ''
- id: :structure_SQ012
  header: structure[SQ012]
  desc: ''
  comment: ''
- id: :values_SQ001
  header: values[SQ001]
  desc: ''
  comment: ''
- id: :values_SQ002
  header: values[SQ002]
  desc: ''
  comment: ''
- id: :values_SQ003
  header: values[SQ003]
  desc: ''
  comment: ''
- id: :values_SQ004
  header: values[SQ004]
  desc: ''
  comment: ''
- id: :values_SQ005
  header: values[SQ005]
  desc: ''
  comment: ''
- id: :secondaryActivities_SQ002
  header: secondaryActivities[SQ002]
  desc: ''
  comment: ''
- id: :secondaryActivities_SQ003
  header: secondaryActivities[SQ003]
  desc: ''
  comment: ''
- id: :secondaryActivities_SQ004
  header: secondaryActivities[SQ004]
  desc: ''
  comment: ''
- id: :secondaryActivities_SQ005
  header: secondaryActivities[SQ005]
  desc: ''
  comment: ''
- id: :secondaryActivities_SQ006
  header: secondaryActivities[SQ006]
  desc: ''
  comment: ''
- id: :secondaryActivities_SQ007
  header: secondaryActivities[SQ007]
  desc: ''
  comment: ''
- id: :secondaryActivities_SQ008
  header: secondaryActivities[SQ008]
  desc: ''
  comment: ''
- id: :secondaryActivities_SQ009
  header: secondaryActivities[SQ009]
  desc: ''
  comment: ''
- id: :secondaryActivities_SQ010
  header: secondaryActivities[SQ010]
  desc: ''
  comment: ''
- id: :secondaryActivities_SQ011
  header: secondaryActivities[SQ011]
  desc: ''
  comment: ''
- id: :secondaryActivities_SQ012
  header: secondaryActivities[SQ012]
  desc: ''
  comment: ''
- id: :secondaryActivities_SQ013
  header: secondaryActivities[SQ013]
  desc: ''
  comment: ''
- id: :attendWorkshop
  header: attendWorkshop
  desc: ''
  comment: ''
