---
id: :ncg
name: NCG
version: 20240929
primary_key:
- :coop_name
comment: 
fields:
- id: :coop_name
  header: Co-op Name
  desc: ''
  comment: ''
- id: :store_name
  header: Store Name
  desc: ''
  comment: ''
- id: :address
  header: Address
  desc: ''
  comment: ''
- id: :address_2
  header: Address Line 2
  desc: ''
  comment: ''
- id: :city
  header: City
  desc: ''
  comment: ''
- id: :state
  header: State
  desc: ''
  comment: ''
- id: :zip
  header: Zip
  desc: ''
  comment: ''
- id: :website
  header: Website
  desc: ''
  comment: ''
